# render.yaml configuration for Baserow, n8n, and ToolJet in Frankfurt region

services:

  - name: n8n
    type: web
    runtime: image
    plan: free
    image: 
      url: n8nio/n8n:latest
    domains:
      - demo.n8n.nenkod.com
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true

      - key: N8N_BASIC_AUTH_USER
        value: "admin"

      - key: N8N_BASIC_AUTH_PASSWORD
        value: "admin"

      - key: N8N_HOST
        value: "demo.n8n.nenkod.com"
      
    autoDeploy: true
    healthCheckPath: "/"
    region: frankfurt

  - name: nocodb
    type: web
    runtime: image
    plan: free
    image:
      url: nocodb/nocodb:latest
    region: frankfurt

  - name: tooljet
    type: web
    runtime: image
    plan: free
    image:
      url: tooljet/tooljet-ce
    domains:
      - demo.tooljet.nenkod.com
    envVars:
      - key: TOOLJET_HOST
        value: https://demo.tooljet.nenkod.com
      - key: SECRET_KEY_BASE
        value: "55f07fde92352b48840033bfc7820061594cb6a616ea852e9d83e1130cc0ac403e593002f305ff93fb14538cc720dfac17afcf78ecc7f4f6132880a5e25224ca"
    region: frankfurt
  
  # - name: appsmith
  #   type: web
  #   runtime: image
  #   plan: free
  #   image:
  #     url: bitnami/appsmith
  #   domains:
  #     - demo.appsmith.nenkod.com
  #   region: frankfurt

  # - name: mongo
  #   type: web
  #   runtime: image
  #   plan: free
  #   image:
  #     url: mongo
  #   region: frankfurt