# render.yaml configuration for Baserow, n8n, and ToolJet in Frankfurt region

services:

  - name: n8n
    type: web
    env: docker
    plan: standard
    image: n8nio/n8n:latest
    envVars:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "admin"
      N8N_BASIC_AUTH_PASSWORD: "your_password"
      N8N_HOST: "https://n8n.yourdomain.com"
      DB_TYPE: "postgresdb"
      DB_POSTGRESDB_HOST: "hostname"
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: "n8n-db"
      DB_POSTGRESDB_USER: "username"
      DB_POSTGRESDB_PASSWORD: "password"
    autoDeploy: true
    healthCheckPath: "/"
    disk:
      name: n8n-data
      sizeGB: 5
    region: frankfurt